### ISSUE TITLE
Increase POKT Token Amount 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/testnet-faucet#12]
The faucet should have a "node" option that has a higher amount of tokens given, so they don't have to click the button 15 times just to get the minimum staking amount. 

or maybe another option would be to just default the faucet to 15000 test POKT tokens and have a disclaimer saying to use responsibly(assuming we have a limited amount of test POKT tokens)

**Comment by nymd** [comment]
What did you decide on the amount @jeremybeal11

**Comment by jeremybeal11** [comment]
let's just leave it at 1000POKT
